import json
import os

def update_locale(file_path, updates):
    with open(file_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    for k, v in updates.items():
        data[k] = v

    with open(file_path, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=4)

new_keys_en = {
    "A oferta excedeu a capacidade de armazenamento dos armazéns. Não há um erro no cálculo, mas sim uma limitação física na infraestrutura de armazenamento disponível para os armazéns utilizados.": "The supply exceeded the storage capacity of the warehouses. There is no calculation error, but rather a physical limitation in the storage infrastructure available for the used warehouses.",
    "Lembre-se da diferença entre Capacidade Local vs. Global: Apenas somar a capacidade total de todos os armazéns habilitados não garante a viabilidade da operação. Se um armazém tiver muito espaço vazio, mas possuir uma 'porta de entrada' (recepção diária) muito estreita ou restrições de frete que forcem envios incompatíveis, o modelo pode ser obrigado a estourar a capacidade física de outro armazém para escoar a carga e não deixar caminhões parados.": "Remember the difference between Local vs. Global Capacity: Merely summing the total capacity of all enabled warehouses does not guarantee operational viability. If a warehouse has plenty of empty space but a very narrow 'entry door' (daily reception) or freight constraints that force incompatible shipments, the model might be forced to exceed the physical capacity of another warehouse to move the cargo and avoid leaving trucks idle.",
    "Suposições do Modelo e Atenção aos Resultados:": "Model Assumptions and Attention to Results:",
    "Estes avisos refletem as escolhas matemáticas que o modelo precisou fazer para contornar gargalos logísticos. Para evitar que o sistema ficasse 'sem solução' e para mostrar exatamente onde a operação 'trava', o modelo preferiu utilizar uma capacidade de armazenamento artificial (como se alugasse um galpão extra de emergência) com um custo/multa exorbitantemente alto. Por isso, os valores de custo total exibidos aqui devem ser desconsiderados até que o gargalo seja resolvido.": "These warnings reflect the mathematical choices the model had to make to bypass logistical bottlenecks. To prevent the system from becoming 'unsolvable' and to show exactly where the operation 'jams', the model preferred to use artificial storage capacity (as if renting an emergency extra warehouse) with an exorbitantly high cost/penalty. Therefore, the total cost values displayed here should be ignored until the bottleneck is resolved.",
    "Verifique se as restrições de Frete Mínimo não estão forçando o envio de cargas maiores do que o armazém suporta receber de uma vez.": "Check if Minimum Freight constraints are not forcing the shipment of loads larger than the warehouse can receive at once.",
    "Interações complexas de regras: A recepção funciona como a 'porta de entrada' do armazém. Mesmo que haja muito espaço interno (capacidade estática) sobrando, se a velocidade com que o armazém consegue receber os caminhões for muito baixa, ocorrerá um gargalo. Além disso, se houver regras rígidas de 'Frete Mínimo', o modelo pode preferir estourar essa 'porta de entrada' para garantir que os caminhões não viagem vazios.": "Complex rule interactions: Reception acts as the 'entry door' of the warehouse. Even if there is plenty of internal space (static capacity) left, if the speed at which the warehouse can receive trucks is too low, a bottleneck will occur. Furthermore, if there are strict 'Minimum Freight' rules, the model may prefer to burst this 'entry door' to ensure trucks do not travel empty.",
    "Estes avisos não são erros de cálculo, mas reflexos de limitações físicas da sua operação. Para evitar que o modelo ficasse 'sem solução', o sistema preferiu 'forçar a entrada' da carga usando uma capacidade de recepção artificial com um custo (multa) exorbitantemente alto. Portanto, os valores de custo total exibidos nesta página devem ser desconsiderados até que a questão seja resolvida.": "These warnings are not calculation errors, but reflections of physical limitations in your operation. To prevent the model from becoming 'unsolvable', the system preferred to 'force the entry' of the cargo using artificial reception capacity with an exorbitantly high cost (penalty). Therefore, the total cost values displayed on this page should be ignored until the issue is resolved.",
    "Aumente a carga máxima de recepção diária ou o número de dias úteis na configuração do modelo para 'alargar a porta de entrada'.": "Increase the maximum daily reception load or the number of working days in the model configuration to 'widen the entry door'.",
    "Distribua melhor a oferta entre outros armazéns habilitados que tenham uma recepção mais rápida.": "Better distribute the supply among other enabled warehouses that have faster reception.",
    "Verifique se as restrições de 'Carga mínima de frete' não estão obrigando o envio de volumes muito grandes de uma só vez para armazéns com recepção lenta.": "Check if 'Minimum freight load' constraints are not forcing the shipment of very large volumes at once to warehouses with slow reception.",
    "Interações complexas de regras: Esse tipo de alerta ocorre quando os dados entram em conflito. Por exemplo, se a sua oferta restante for de 10 toneladas, mas você configurou que um caminhão só viaja se tiver no mínimo 30 toneladas (Frete Mínimo), essa sobra de 10 toneladas ficará travada na origem. O mesmo ocorre se um armazém só puder receber 15 toneladas por dia, mas o seu caminhão mínimo carrega 30 toneladas: o modelo não tem como fazer a entrega sem quebrar alguma regra.": "Complex rule interactions: This type of alert occurs when data conflicts. For example, if your remaining supply is 10 tons, but you configured that a truck only travels if it has at least 30 tons (Minimum Freight), this remaining 10 tons will be stuck at the origin. The same happens if a warehouse can only receive 15 tons per day, but your minimum truck carries 30 tons: the model cannot make the delivery without breaking a rule.",
    "Não se trata de um erro no sistema, mas de um beco sem saída logístico. Nessas situações, em vez de não entregar nada, o modelo assume que essa carga problemática simplesmente não pôde ser alocada e aplica uma penalidade (multa) altíssima no custo total. Desconsidere os custos exibidos até ajustar os limites.": "It is not a system error, but a logistical dead end. In these situations, instead of delivering nothing, the model assumes that this problematic cargo simply could not be allocated and applies a very high penalty (fine) to the total cost. Disregard the displayed costs until you adjust the limits.",
    "Reduza a exigência de 'Carga mínima de frete' na configuração do modelo para permitir que caminhões mais vazios façam o transporte das sobras.": "Reduce the 'Minimum freight load' requirement in the model configuration to allow emptier trucks to transport the leftovers.",
    "Certifique-se de que as quantidades ofertadas totais são múltiplos ou compatíveis com os limites de carga estabelecidos.": "Ensure that the total supplied quantities are multiples of or compatible with the established load limits.",
    "Verifique se os armazéns de destino possuem 'Capacidade de Recepção Diária' suficiente para receber ao menos um caminhão inteiro do tamanho mínimo exigido.": "Check if the destination warehouses have enough 'Daily Reception Capacity' to receive at least one full truck of the minimum required size."
}

new_keys_pt = {k: k for k in new_keys_en.keys()}

update_locale('src/locales/en.json', new_keys_en)
update_locale('src/locales/pt.json', new_keys_pt)
